### ISSUE TITLE
Not possible to uninstall?

### ISSUE THREAD

**Issue by whitfin** [skotchpine/asdf-java#1]
Looks like it creates a bunch of read only stuff... any reason why?

**Comment by skotchpine** [comment]
I'm seeing something like this now, yea. Are you on Linux, mingw, cygwin, OSX, other BSD?

**Comment by whitfin** [comment]
I'm on OS X 10.12.5 (16F73) :)

**Comment by skotchpine** [comment]
Same, today. So, it looks like the sutffs are read-only because hdiutil fails to unmount the java dist. I'll have a patch soon.

**Comment by skotchpine** [comment]
The issue should be resolved. Thanks for catching this, @whitfin!
