### ISSUE TITLE
Unable to install any version of java

### ISSUE THREAD

**Issue by vraravam** [skotchpine/asdf-java#10]
I would like to install `8.151` and `9.0.4` - but both of them hang in the `downloading...` step. There's no movement at all - even though I have let the process run for almost 30 mins. Could there be a way to debug what's going on?

**Comment by vraravam** [comment]
`8.161` downloaded after 30+ mins, but when I run `which java`, I still get the system default one.

**Comment by vraravam** [comment]
This also took a long time. Now, I have everything working. btw, I had to do a reshim AND reopen my terminal app for all changes to take effect.

**Comment by skotchpine** [comment]
I see that I may have dropped the ball on this one. I've been busy with work lately, and I apologize for leaving you hanging.

Glad you're set up now, and I hope you're still comfortable posting any issues you have here.

As for the lengthy download and unpacking, I'd like to provide an interface to increase the logging and curl robustness. I'll make some organizational progress toward than end shortly.

Thanks for the interest, @vraravam. :nerd_face: :
