### ISSUE TITLE
$JAVA_HOME

### ISSUE THREAD

**Issue by tofagerl** [skotchpine/asdf-java#13]
I'm sorry if I'm being incredibly thick, but how can I set JAVA_HOME to whichever jvm is set as global atm?
I'm used to just having something like $HOME/.asdf/installs/java/global so that I can use that to set JAVA_HOME in scripts.

Obviously this wouldn't work in directories where .tool-versions is set to another version, but that's not a problem.

**Comment by mcdan** [comment]
This is a little script I use to set JAVA_HOME based on whatever java asdf has made available.
`asdf current java > /dev/null || export JAVA_HOME=$(asdf where java $(asdf current java | cut -d ' ' -f 1))`
Hth.

**Comment by whaley** [comment]
@mcdan I believe should be an `&&` and not `||`.

**Comment by mcdan** [comment]
Fixed, thanks.

**Comment by tofagerl** [comment]
Sweet script, thanks!

**Comment by skotchpine** [comment]
@tofagerl, glad you brought this up. @mcdan & @whaley, adding your thing to the readme as a suggested line to shell init. 😃
