### ISSUE TITLE
Consider Supporting AdoptOpenJDK and/or Zulu

### ISSUE THREAD

**Issue by whaley** [skotchpine/asdf-java#16]
In the event users of asdf wish to use a non-oracle distribution, options for a version could include releases from the following:

- https://adoptopenjdk.net/releases.html
- https://www.azul.com/downloads/zulu/

I propose including publicly exposed versions of these JDKs in asdf-java's versions.  This means that each version number needs to be qualified also with the distribution - e.g. "oracle-10.0.1",  "openjdk-hotspot-10+23" would be versions to select from instead.  

Since this adds more choices, which isn't always a good thing, I'd be interested to hear if others would prefer this, or if supporting oracle jdks only is sufficient enough.

**Comment by skotchpine** [comment]
@whaley, this is a great idea. I definitely want to see this

**Comment by skotchpine** [comment]
Might create a project for this soon.

**Comment by hubertlepicki** [comment]
I guess that would also mean we get to have older versions available, as in v 1.7? I am using jabba instead of asdf-java for that purpose only at the moment, and would love to unify everything under asdf vm :)

**Comment by skotchpine** [comment]
Thanks for the motivation, @hubertlepicki!

**Comment by skotchpine** [comment]
We have openjdk now!
