### ISSUE TITLE
Fails to install java 8

### ISSUE THREAD

**Issue by unicolet** [skotchpine/asdf-java#2]
Tried all java 8 versions listed by `list-all` but they all fail.

```
asdf install java 8.141
---- ASDF JAVA MESSAGE ----
downloading: http://download.oracle.com/otn-pub/java/jdk/8.141-b15/336fa29ff2bb4ef291e347e091f7f4a7/jdk-8.141-linux-x64.tar.gz
---- ASDF JAVA ERROR ----
asdf java failed while downloading java dist
```

It appears the first url sends a redirect to: `Location: https://edelivery.oracle.com/otn-pub/java/jdk/8.121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8.121-linux-x64.tar.gz`

Which then must have some further validation/authentication stuff going on because it eventually returns an HTML page with a 404.

**Comment by skotchpine** [comment]
I'm seeing this behavior for 8.144 and 8.121 today, but installed 9.0.1, 8.131 and 8.141 successfully.

I'm not convinced it's authentication missing on our end. Last night I followed the failing redirect for 8.141 by hand and it was fine. I'll try to replicate that sometime soon.

**Comment by unicolet** [comment]
@skotchpine thanks for checking, I'll give it a look again as soon as I can. Oracle is not exactly friendly 😠

**Comment by unicolet** [comment]
9.0.1 worked for me as well, btw

**Comment by skotchpine** [comment]
@unicolet Good to hear that works for you. Still, *versions* would be nice. Not sure how to navigate oracle. I may reach out to others doing similar things

**Comment by unicolet** [comment]
@skotchpine apparently 8.141 and 8.131 work today. 8.144 still busted :-(

**Comment by unicolet** [comment]
curiously enough this has not happened since, closing. Thanks :-)

**Comment by aexmachina** [comment]
I'm still having this problem. 8.141 works, but every version after it doesn't work.

**Comment by croaky** [comment]
@aexmachina Does https://github.com/skotchpine/asdf-java/pull/14 help?

**Comment by aexmachina** [comment]
@croaky yes, that fixed the problem.
