### ISSUE TITLE
JAVA_HOME export not working

### ISSUE THREAD

**Issue by rafaeltoledo** [skotchpine/asdf-java#24]
Seem to be a problem with spacing, as `asdf current java` is returning `oracle-8.181(set by /Users/rafaeltoledo/.tool-versions)`

**Comment by whaley** [comment]
Confirmed as not working:
```
➜  ~ asdf_update_java_home() {
  local current
  if current=$(asdf current java); then
    local version=$(echo $current | cut -d ' ' -f 1)
    export JAVA_HOME=$(asdf where java $version)
  else
    echo "No java version set. Type `asdf list-all java` for all versions."
  fi
}

➜  ~ asdf_update_java_home 
➜  ~ echo $JAVA_HOME
Version not installed
➜  ~ asdf current java
openjdk-10.0.2(set by /home/whaley/.tool-versions)
➜  ~ echo $(asdf current java) | cut -d ' ' -f 1
openjdk-10.0.2(set
```

**Comment by whaley** [comment]
Per https://github.com/asdf-vm/asdf/blame/master/lib/commands/current.sh#L22 the way `asdf current java` is output is to be expected.  README.md was updated per instructions in #13 , so perhaps we just need to tweak that cut command to compensate for the time being.
