### ISSUE TITLE
OpenJDK installation fails on macOS

### ISSUE THREAD

**Issue by bpollack** [skotchpine/asdf-java#26]
If I'm understanding what's happening here correctly, the issue is that `asdf` is trying to download a `.dmg`, but the OpenJDK is actually distributed as a tarball with extension `.tar.gz`. I'll try myself to get a patch later, but for now, I at least wanted to log the bug.

**Comment by vraravam** [comment]
This is the exact problem with trying to install `openjdk-10.0.2` on mac os.

**Comment by skotchpine** [comment]
Looks like Travis fails to clone `asdf` even... How does the current `asdf-java` work on your machines?

**Comment by skotchpine** [comment]
YAY! [openjdk-11 build](https://travis-ci.org/skotchpine/asdf-java/jobs/450333911) passed on MacOS.

Couldn't find any working 10.0.2 links, myself. Please make a PR if you find a working dist.
