### ISSUE TITLE
oracle-8.181 installation is failing, replace with oracle-8.191

### ISSUE THREAD

**Issue by vanjabucic** [skotchpine/asdf-java#36]
The download link to 8.181 is failing (probably since Oct 16).
New link is:
http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz

**Comment by skotchpine** [comment]
About to push a change addressing this. Removes 8.181, adds 8.191. Will close then. Thanks, @vanjabucic! :+1:
