### ISSUE TITLE
Implement Pending asdf Feature: 'load-env'

### ISSUE THREAD

**Issue by unicolet** [skotchpine/asdf-java#5]
I have a system JDK installed in `/usr/lib/jvm/java-8-oracle` which sets JAVA_HOME.

Now when I switch to the JDK supplied by `asdf-java` (by entering a project directory) this does not get overridden, leading to erratic behavior with tools that rely on JAVA_HOME (i.e. maven).

**Comment by skotchpine** [comment]
Good catch. Embarrassed I didn't realize that. So, we need some hook in asdf, eh? Thanks for taking the lead on these things.

**Comment by skotchpine** [comment]
Leaving this open, possibly as an 'implement asdf feature X'?

**Comment by skotchpine** [comment]
So... I redid the title like three times and stuff. :100:

**Comment by skotchpine** [comment]
Hah, goddam

**Comment by skotchpine** [comment]
@unicolet kk
